name: NodeJS with Webpack

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Get version from package.json
      id: package.json
      uses: actions/github-script@v7
      with: 
        script: |
         const packageJson = require('./package.json');
         core.setOutput('version', packageJson.version);

    - name: Use the version number
      run: |
        THEME_VERSION="${{ steps.package.outputs.version }}"
        echo "The version is: $THEME_VERSION"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: unity_canvas_theme_${{ theme. }}
        path: build/
